version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: defaultdb
  spicedb-engine-migrate:
    image: quay.io/authzed/spicedb:latest
    depends_on:
     - postgres
    command: migrate head
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: somerandomkey
      SPICEDB_LOG_LEVEL: debug
      SPICEDB_DATASTORE_ENGINE: postgres 
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:secret@postgres:5432/postgres?sslmode=disable
  spicedb-engine:
    image: quay.io/authzed/spicedb:latest
    restart: always
    ports:
    - "8080:8080"
    - "8443:8443"
    - "9090:9090"
    - "50051:50051"
    depends_on:
     - spicedb-engine-migrate
    command: serve 
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: somerandomkey
      SPICEDB_LOG_LEVEL: debug
      SPICEDB_DATASTORE_ENGINE: postgres 
      SPICEDB_HTTP_ENABLED: true 
      SPICEDB_DATASTORE_CONN_URI: postgres://postgres:secret@postgres:5432/postgres?sslmode=disable
volumes:
  db_data:
